import os
import psycopg2
import psycopg2.extras

DATABASE_URL = os.environ.get('DATABASE_URL', 'postgresql://localhost/vargani')

RESIDENTS = {
    "001": "JYOTI ANKUSH RENUSE",
    "002": "SHALUBAI G KURADE",
    "003": "BABAJI AAPPA GAWALI",
    "004": "DEVENDRA K JAIN",
    "005": "NARAYAN B PUJARI",
    "006": "JAIPRAKASH P GUPTA",
    "007": "MAHADEVI REDDY",
    "008": "KARULAL P JAIN",
    "009": "BIMAMMA SAYAMMA",
    "010": "SHIVCHARANPPA POOJARI",
    "011": "ASMITA ABHIJEET LAKHAMJE",
    "012": "PUSHPLATA C DORLE",
    "013": "PAWAN D JAIN",
    "014": "PRAMILA PAWAN JAIN",
    "015": "WELFARE CENTER",
    "016": "WELFARE CENTER",
    "017": "SOCIETY OFFICE",
    "018": "BAALWADI",
    "019": "BAALWADI",
    "020": "VENKATESH. C. MEDAK",
    "021": "SHRIPAD S SALVEKAR",
    "022": "PRAVIN S SALVEKAR",
    "023": "VIJAY R GHADGE",
    "024": "METER ROOM",
    "101": "BALAPPA DHOBI",
    "102": "SABAMMA DHANGAR",
    "103": "KALPANA MISTRY",
    "104": "RATNAKAR G. SANGLUKAR",
    "105": "MAZAR KHAN",
    "106": "YASHWANT U BONDE",
    "107": "SORNAPRABHA B NADAR",
    "108": "MALAPPA S KOTGIRI",
    "109": "LAXMI RAJESH PADAM",
    "110": "BHAVNA AMIT SHELKE",
    "111": "TIMMA B JAMLAPPA",
    "112": "JITENDRA MANOHAR KOLPATE",
    "113": "DEVAMMA N HARIJAN",
    "114": "BABAMMA NARSAPPA",
    "115": "CHANDRABHAGA D ADANGALE",
    "116": "LAXMIBAI D BIJ",
    "117": "LAXMAN B IDLOOR",
    "118": "SITARAM R RANE",
    "119": "DURGADEVI I BUCHALA",
    "120": "NARENDRA N HARIJAN",
    "121": "SHALINI DADU YADAV",
    "122": "VENKATRAMUL C MEDAK",
    "123": "MOHAN B KURADE",
    "124": "SANTOSH R YADAV",
    "201": "NITIN J AMRE",
    "202": "",
    "203": "NARSIMLU BHIMAPPA KINDIGERI",
    "204": "VICTOR G ALMEIDA",
    "205": "ANITA BHEEMAPPA JOGU",
    "206": "MAYA V GAWAI",
    "207": "AJAY S GUPTA",
    "208": "DEEPAK B KURADE",
    "209": "NARSAMMA MOGLLAPPA",
    "210": "VISHWAS B KURANE",
    "211": "CHANDRYA H JOGU",
    "212": "MANIKAPPA GALA",
    "213": "YELLAMMA A MORE",
    "214": "SHAMAPPA NARSAPPA",
    "215": "DOLCY KINNY",
    "216": "STANY G ALMEIDA",
    "217": "SHIFA M RAFIQUE SAYYED",
    "218": "VIDHYADEVI S GUPTA",
    "219": "NARSING B BHOTU",
    "220": "HANMANTA MANIGIRI",
    "221": "RATANSINGH T KATAKA",
    "222": "HANMANTRAO A PATIL",
    "223": "KIRAN MORE",
    "224": "NARSAMMA DASARI",
    "301": "ISHWARI BUDHA",
    "302": "VINAYAK S MORE",
    "303": "MALTHI R SUTAR",
    "304": "ANJALAPPA B DHANGAR",
    "305": "RAMLU HANMANTA",
    "306": "SUMIT B SHINDE",
    "307": "NAZARE ALAM AFTAB ALAM SYED",
    "308": "BALBIRSINGH S ROHDIYA",
    "309": "MALIKARJUN POOJARI",
    "310": "SUNITA SACHIN CHANDALIYA",
    "311": "SHRUTI SANTOSH CHAVAN",
    "312": "RAJWANTI KAROTHIYA",
    "313": "OMPRAKASH KAROTHIYA",
    "314": "THAYULLATHI SEEJU",
    "315": "JANARDAN Y DASARI",
    "316": "VAISHALI V KARNDE",
    "317": "SAVKAR B SHINDE",
    "318": "SHRIDHAR S KURADE",
    "319": "NARENDRA LAXMANAPPA JOGU",
    "320": "HANMANTA B KANKOMAL",
    "321": "CHANAPPA V MEDAK",
    "322": "MAHARANIDEVI S ROHDIYA",
    "323": "DESMOND D`SOUZA",
    "324": "DEVAMMA B GANDMINA",
    "401": "RAMLAMMA BHIMAPPA KINDIGERI",
    "402": "USHENAPPA REDDY",
    "403": "ROHINI SUNIL PAWAR",
    "404": "ROLAN G ALMEIDA",
    "405": "CHANDRAMMA H JOGU",
    "406": "LATA NAGA PUJARI",
    "407": "MALAMMA L KESHWAR",
    "408": "ASHWINI PUNDLIK SAWANT",
    "409": "CHANDRAKANT NAMDEV SHINDE",
    "410": "VANDNA RANI",
    "411": "NARAYAN S RAWOOL",
    "412": "MANOHAR R PATIL",
    "413": "FATEMA SAMEER SAYYED",
    "414": "VILAS K PATEL",
    "415": "DEVAMMA MAHADEV",
    "416": "SADANAND S ASHYARI",
    "417": "HIRABAI M CHAVAN",
    "418": "PRABHAKAR M CHAVAN",
    "419": "KALAWATI S SALVEKAR",
    "420": "KISHOR S SALVEKAR",
    "421": "SALUBAI GHODKE",
    "422": "CHANDBI NABISHAB",
    "423": "PREMDAS T CHOWHAN",
    "424": "RAMESH G BORKAR",
    "501": "HIRABAI G HINGMIRE",
    "502": "HANMANTA M KOTGIRE",
    "503": "ANITA ASHOK PALAV",
    "504": "ANAND M SUTAR",
    "505": "BHUDEVI B KAROTHIYA",
    "506": "SAKHUBAI DINKAR AHER",
    "507": "MALLESH N VAGGAN",
    "508": "SHERIFA MOHAMMAD",
    "509": "BAPU A KHARTHARE",
    "510": "SAVITRI MALLESH DAYAL",
    "511": "BICHAMMA S NEERETI",
    "512": "RAMLU GANDMALA",
    "513": "MANJULA R BIJ",
    "514": "YELLAPPA N JOGU",
    "515": "KAMLAMMA HANMANTA",
    "516": "JITENDRA MANOHAR DONGRE",
    "517": "NIRMALA P ARYA",
    "518": "CHANDRAPPA A NIRETI",
    "519": "BHIMRAO H SULTANPUR",
    "520": "PRABHAT MUKUND PATEKAR",
    "521": "SHAMBAJI T KHANVILKAR",
    "522": "YENKOBA DASARI",
    "523": "CLYDE G ALMEIDA",
    "524": "ANTANA NIRETI",
    "601": "PREMSINGH J RAWAL",
    "602": "ANAND MOGLAPPA JOGU",
    "603": "ANANDRAO B SUTAR",
    "604": "MEGHA PRAMOD SUTAR",
    "605": "RAZA ABBAS M A KHAN",
    "606": "SANJAY S GUPTA",
    "607": "PRADNYA P KADAM",
    "608": "LAXMAN B BACCHE",
    "609": "PASCAOL BAYLON KINNY",
    "610": "YENKAPPA HANMANTA",
    "611": "MEENAKSHI A WADEKAR",
    "612": "VICTOR G FERNANDES",
    "613": "MANOJ R KHATKA",
    "614": "SONIA ROYAL MATHAIS",
    "615": "BHIMA MALLAPPA KOTGIRI",
    "616": "KAMLA RAJENDRA GOLI",
    "617": "HANMANTA NARSAPPA",
    "618": "MUKTABAI L KHARADE",
    "619": "MOHAMMAD ALI RATHOD",
    "620": "MAHADEV M SURAI",
    "621": "SHAMRAO J PATIL",
    "622": "SANDEEP ZIPRU WAGH",
    "623": "KAVITA ANIL SHINDE",
    "624": "RAMBAJI B SHINDE",
    "701": "CHANDRAMMA MOGLAPPA",
    "702": "",
    "703": "SASAMMA SAYAPPA",
    "704": "MANOHAR B SUTAR",
    "705": "",
    "706": "ANITA VENKATESH MEDAK",
    "707": "",
    "708": "",
    "709": "DEVAPPA IRSALE",
    "710": "MALTI M BHARADE",
    "711": "",
    "712": "",
    "713": "",
    "714": "",
    "715": "",
    "716": "",
    "717": "",
    "718": "",
    "719": "",
    "720": "",
    "721": "MANILAL GALA",
    "722": "SAYAMMA MALLAPPA",
    "723": "PHILOMENA CASSION DIAS",
    "724": "ARCHANA KRISHNA CHAWAN"
}

def update_residents():
    try:
        conn = psycopg2.connect(DATABASE_URL)
        cursor = conn.cursor()
        updated_count = 0
        for flat_no, owner_name in RESIDENTS.items():
            floor = int(flat_no[0]) if len(flat_no) == 3 else 0
            cursor.execute('''
                INSERT INTO flats (flat_no, floor, owner_name)
                VALUES (%s, %s, %s)
                ON CONFLICT (flat_no) DO UPDATE SET owner_name = EXCLUDED.owner_name
                WHERE flats.owner_name IS NULL OR flats.owner_name = '' OR flats.owner_name != EXCLUDED.owner_name
            ''', (flat_no, floor, owner_name))
            updated_count += cursor.rowcount
        conn.commit()
        cursor.close()
        conn.close()
        print(f"Successfully updated {updated_count} flat owner records.")
    except Exception as e:
        print("Error updating database residents:", e)

if __name__ == "__main__":
    update_residents()
